# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-27 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0, null=True)),
                ('image', models.ImageField(blank=True, upload_to=None)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('rating', models.IntegerField(default=5, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='products.Product')),
            ],
            options={
                'verbose_name': 'Product Detail',
                'verbose_name_plural': 'Product Details',
            },
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='productdetails',
            unique_together=set([('product', 'category')]),
        ),
    ]
